baseURL: https://jacopodonati.it/
title: Jacopo Donati
defaultContentLanguage: it

theme: chimero

copyright: "© jacopo donati"

module:
  imports:
  - path: "github.com/jacopodonati/hugo-theme-chimero"