baseURL: https://jacopodonati.it/
title: Jacopo Donati
defaultContentLanguage: it

copyright: "© Jacopo Donati"

params:
  light_chrome: "#fafaf9"
  dark_chrome: "#23201f"

  profile:
    logline: "Scrittore, editor, e docente"
    location: "Bologna"