title: Jacopo Donati
email: jacopo@jacopodonati.it
description: 🍕🍕
baseurl: ""
url: "https://jacopodonati.it"
github_username:  jacopodonati
twitter_username:  _jacopodonati
mastodon_username:  'https://mastodon.online/@jacopodonati'
copyright: "© Jacopo Donati"
author: Jacopo Donati

collections:
  corsi:
    output: true
    permalink: /:collection/:name
  manuale:
    output: true
    permalink: /:collection/:name
  pubblicazioni:
    output: true
    permalink: /:collection/:name
  spoiler:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "manuale"
    values:
      layout: "scheda"
      category: "Manuale per vivere"
  -
    scope:
      path: ""
      type: "spoiler"
    values:
      layout: "spoiler"
      category: "Spoiler"

theme: chimero
remote_theme: jacopodonati/jekyll-theme-chimero
plugins:
  - jekyll-feed

colors:
  light_chrome: '#f9f7f6'
  dark_chrome: '#23201f'

avatar:
  path: /img/
  size_full: profile.jpg
  size_1x: profile@1x.jpg
  size_2x: profile@2x.jpg
  size_3x: profile@3x.jpg
  size_4x: profile@4x.jpg

feed:
  posts_limit: 666
  collections:
    - manuale
    - spoiler