title: 'Jacopo Donati'
email: 'jacopo@jacopodonati.it'
description: 'Da più di dieci anni racconto storie e insegno a raccontarle con corsi per adulti e ragazzi, che siano appassionati o che vogliano farne una professione.'
baseurl: ''
url: 'https://jacopodonati.it'
github_username:  'jacopodonati'
twitter_username:  '_jacopodonati'
mastodon_username:  'https://mastodon.online/@jacopodonati'
copyright: '© Jacopo Donati'
author: 'Jacopo Donati'

collections:
  corsi:
    output: true
    permalink: /:collection/:name
  manuale:
    output: true
    permalink: /:collection/:name
  pubblicazioni:
    output: true
    permalink: /:collection/:name
  spoiler:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ''
      type: 'manuale'
    values:
      layout: 'scheda'
      category: 'Manuale per vivere'
  -
    scope:
      path: ''
      type: 'spoiler'
    values:
      layout: 'spoiler'
      category: 'Spoiler'

# remote_theme: jacopodonati/jekyll-theme-chimero
# theme: chimero

plugins:
  - jekyll-feed

colors:
  light_chrome: '#f9f7f6'
  dark_chrome: '#23201f'

avatar:
  path: profile/
  filename: profile.jpg

feed:
  posts_limit: 666
  collections:
    - manuale
    - spoiler

picture:
  source: "assets/img/_fullsize"
  output: "assets/img/_generated"
  suppress_warnings: true
