baseURL = 'https://www.jacopodonati.it/'
defaultContentLanguage = 'it'
title = 'Jacopo Donati'

ignoreFiles = ['#\.']

sectionPagesMenu = 'main'
# uglyURLs = true

theme = 'no-frills'

[author]
given_name = 'Jacopo'
family_name = 'Donati'
display_name = 'Jacopo Donati'

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = true
[languages]
  [languages.it]
    disabled = false
    languageCode = 'it'
    languageDirection = 'ltr'
    languageName = 'Italiano'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true
