baseURL = 'https://www.jacopodonati.it/'
defaultContentLanguage = 'it'
title = 'Jacopo Donati'
theme = 'no-frills'

ignoreFiles = ['#\.']

[author]
given_name = 'Jacopo'
family_name = 'Donati'
display_name = 'Jacopo Donati'

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = true
[languages]
  [languages.it]
    disabled = false
    languageCode = 'it'
    languageDirection = 'ltr'
    languageName = 'Italiano'
    weight = 1
    [languages.it.menus]
      [[languages.it.menus.main]]
        pageRef = 'libri'
        identifier = 'menu_libri'
        weight = 20
      [[languages.it.menus.main]]
        pageRef = 'manuale'
        identifier = 'menu_manuale'
        weight = 30
      [[languages.it.menus.main]]
        pageRef = 'cose-belle'
        identifier = 'menu_cose_belle'
        weight = 40
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        pageRef = 'libri'
        identifier = 'menu_libri'
        weight = 20
      [[languages.en.menus.main]]
        pageRef = 'manuale'
        identifier = 'menu_manuale'
        weight = 30
      [[languages.en.menus.main]]
        pageRef = 'cose-belle'
        identifier = 'menu_cose_belle'
        weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[menus]

  