baseURL = 'https://www.jacopodonati.it/'
defaultContentLanguage = 'it'
title = 'Jacopo Donati'
theme = 'no-frills'

ignoreFiles = ['#\.']

[author]
given_name = 'Jacopo'
family_name = 'Donati'
display_name = 'Jacopo Donati'

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = true
[languages]
  [languages.it]
    disabled = false
    languageCode = 'it'
    languageDirection = 'ltr'
    languageName = 'Italiano'
    weight = 1
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[menus]

  [[menus.main]]
  name = 'libri'
  identifier = 'menu_libri'
  pageRef = '/libri'
  weight = 20
  
    [[menus.main.libri]]
    parent = 'libri'
    name = 'black'
    identifier = 'menu_libri_black'
    pageRef = '/libri/9788866568315'

  [[menus.main]]
  name = 'cose belle'
  pageRef = '/cose-belle'
  identifier = 'menu_cose_belle'
  weight = 40

  [[menus.main]]
  name = 'manuale per vivere'
  identifier = 'menu_manuale'
  pageRef = '/manuale'
  weight = 30