name: Scribacchino alla ribalta

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Zsh
      run: sudo apt-get install -y zsh

    - name: Run build script
      run: |
        zsh scribacchino.sh

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './public'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
